name: 2x2
tag: mr6-4
version: 6.4
crs_files: [data/proto_nd_flow/multi_tile_layout-2.4.16_v4.yaml, data/proto_nd_flow/multi_tile_layout-2.5.16_v4.yaml]
lrs_file: data/proto_nd_flow/light_module_desc-4.0.0.yaml
tpc:
  dimensions: [30.431, 124.152, 62.076]
  module_ids: [0, 0, 1, 1, 2, 2, 3, 3]
  positions:
  - [48.8743, 0.0, 33.5]
  - [18.1258, 0.0, 33.5]
  - [48.8743, 0.0, -33.5]
  - [18.1258, 0.0, -33.5]
  - [-18.1258, 0.0, 33.5]
  - [-48.8743, 0.0, 33.5]
  - [-18.1258, 0.0, -33.5]
  - [-48.8743, 0.0, -33.5]
optical:
  volume: tpc
  shape: [box, box]
  mirror: true
  dimensions:
  - [27.17, 31.02, 1.0]
  - [27.17, 10.34, 1.0]
  shape_ids: [0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1]
  det_ids: [0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7,
    8, 8, 8, 8, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 14, 14,
    15, 15]
  positions:
  - [0, -46.53, -31.49]
  - [0, -25.85, -31.49]
  - [0, -15.51, -31.49]
  - [0, -5.16, -31.49]
  - [0, 15.51, -31.49]
  - [0, 36.19, -31.49]
  - [0, 46.53, -31.49]
  - [0, 56.87, -31.49]
  - [0, -46.53, 31.49]
  - [0, -25.84, 31.49]
  - [0, -15.51, 31.49]
  - [0, -5.17, 31.49]
  - [0, 15.51, 31.49]
  - [0, 36.19, 31.49]
  - [0, 46.53, 31.49]
  - [0, 56.87, 31.49]
