name: SBND
tag: sbndv2-4
version: 2.4
gdml: sbnd_v02_04.gdml
tpc:
  dimensions: [201.4, 400.015, 501.315]
  module_ids: [0, 0]
  positions:
  - [-100.9, 0.0, 254.7]
  - [100.9, 0.0, 254.7]
optical:
  volume: module
  global_index: true
  shape: [box, ellipsoid]
  dimensions:
  - [0.2, 20.6, 7.6]
  - [10.1601, 20.32, 20.32]
  shape_ids: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 0]
  positions:
  - [-213.75, -135.0, -234.4458]
  - [213.75, -135.0, -234.4458]
  - [-213.75, 0.0, -234.4458]
  - [213.75, 0.0, -234.4458]
  - [-213.75, 135.0, -234.4458]
  - [213.75, 135.0, -234.4458]
  - [-213.4, -175.0, -226.8258]
  - [213.4, -175.0, -226.8258]
  - [-213.4, -95.0, -226.8258]
  - [213.4, -95.0, -226.8258]
  - [-213.4, -40.0, -226.8258]
  - [213.4, -40.0, -226.8258]
  - [-213.4, 40.0, -226.8258]
  - [213.4, 40.0, -226.8258]
  - [-213.4, 95.0, -226.8258]
  - [213.4, 95.0, -226.8258]
  - [-213.4, 175.0, -226.8258]
  - [213.4, 175.0, -226.8258]
  - [-213.75, -135.0, -219.2058]
  - [213.75, -135.0, -219.2058]
  - [-213.75, 0.0, -219.2058]
  - [213.75, 0.0, -219.2058]
  - [-213.75, 135.0, -219.2058]
  - [213.75, 135.0, -219.2058]
  - [-213.75, -175.0, -204.4458]
  - [213.75, -175.0, -204.4458]
  - [-213.75, -95.0, -204.4458]
  - [213.75, -95.0, -204.4458]
  - [-213.75, -40.0, -204.4458]
  - [213.75, -40.0, -204.4458]
  - [-213.75, 40.0, -204.4458]
  - [213.75, 40.0, -204.4458]
  - [-213.75, 95.0, -204.4458]
  - [213.75, 95.0, -204.4458]
  - [-213.75, 175.0, -204.4458]
  - [213.75, 175.0, -204.4458]
  - [-213.4, -135.0, -196.8258]
  - [213.4, -135.0, -196.8258]
  - [-213.4, 0.0, -196.8258]
  - [213.4, 0.0, -196.8258]
  - [-213.4, 135.0, -196.8258]
  - [213.4, 135.0, -196.8258]
  - [-213.75, -175.0, -189.2058]
  - [213.75, -175.0, -189.2058]
  - [-213.75, -95.0, -189.2058]
  - [213.75, -95.0, -189.2058]
  - [-213.75, -40.0, -189.2058]
  - [213.75, -40.0, -189.2058]
  - [-213.75, 40.0, -189.2058]
  - [213.75, 40.0, -189.2058]
  - [-213.75, 95.0, -189.2058]
  - [213.75, 95.0, -189.2058]
  - [-213.75, 175.0, -189.2058]
  - [213.75, 175.0, -189.2058]
  - [-213.75, -135.0, -174.4458]
  - [213.75, -135.0, -174.4458]
  - [-213.75, 0.0, -174.4458]
  - [213.75, 0.0, -174.4458]
  - [-213.75, 135.0, -174.4458]
  - [213.75, 135.0, -174.4458]
  - [-213.4, -175.0, -166.8258]
  - [213.4, -175.0, -166.8258]
  - [-213.4, -95.0, -166.8258]
  - [213.4, -95.0, -166.8258]
  - [-213.4, -40.0, -166.8258]
  - [213.4, -40.0, -166.8258]
  - [-213.4, 40.0, -166.8258]
  - [213.4, 40.0, -166.8258]
  - [-213.4, 95.0, -166.8258]
  - [213.4, 95.0, -166.8258]
  - [-213.4, 175.0, -166.8258]
  - [213.4, 175.0, -166.8258]
  - [-213.75, -135.0, -159.2058]
  - [213.75, -135.0, -159.2058]
  - [-213.75, 0.0, -159.2058]
  - [213.75, 0.0, -159.2058]
  - [-213.75, 135.0, -159.2058]
  - [213.75, 135.0, -159.2058]
  - [-213.75, -135.0, -101.162]
  - [213.75, -135.0, -101.162]
  - [-213.75, 0.0, -101.162]
  - [213.75, 0.0, -101.162]
  - [-213.75, 135.0, -101.162]
  - [213.75, 135.0, -101.162]
  - [-213.4, -175.0, -93.542]
  - [213.4, -175.0, -93.542]
  - [-213.4, -95.0, -93.542]
  - [213.4, -95.0, -93.542]
  - [-213.4, -40.0, -93.542]
  - [213.4, -40.0, -93.542]
  - [-213.4, 40.0, -93.542]
  - [213.4, 40.0, -93.542]
  - [-213.4, 95.0, -93.542]
  - [213.4, 95.0, -93.542]
  - [-213.4, 175.0, -93.542]
  - [213.4, 175.0, -93.542]
  - [-213.75, -135.0, -85.922]
  - [213.75, -135.0, -85.922]
  - [-213.75, 0.0, -85.922]
  - [213.75, 0.0, -85.922]
  - [-213.75, 135.0, -85.922]
  - [213.75, 135.0, -85.922]
  - [-213.75, -175.0, -71.162]
  - [213.75, -175.0, -71.162]
  - [-213.75, -95.0, -71.162]
  - [213.75, -95.0, -71.162]
  - [-213.75, -40.0, -71.162]
  - [213.75, -40.0, -71.162]
  - [-213.75, 40.0, -71.162]
  - [213.75, 40.0, -71.162]
  - [-213.75, 95.0, -71.162]
  - [213.75, 95.0, -71.162]
  - [-213.75, 175.0, -71.162]
  - [213.75, 175.0, -71.162]
  - [-213.4, -135.0, -63.542]
  - [213.4, -135.0, -63.542]
  - [-213.4, 0.0, -63.542]
  - [213.4, 0.0, -63.542]
  - [-213.4, 135.0, -63.542]
  - [213.4, 135.0, -63.542]
  - [-213.75, -175.0, -55.922]
  - [213.75, -175.0, -55.922]
  - [-213.75, -95.0, -55.922]
  - [213.75, -95.0, -55.922]
  - [-213.75, -40.0, -55.922]
  - [213.75, -40.0, -55.922]
  - [-213.75, 40.0, -55.922]
  - [213.75, 40.0, -55.922]
  - [-213.75, 95.0, -55.922]
  - [213.75, 95.0, -55.922]
  - [-213.75, 175.0, -55.922]
  - [213.75, 175.0, -55.922]
  - [-213.75, -135.0, -41.162]
  - [213.75, -135.0, -41.162]
  - [-213.75, 0.0, -41.162]
  - [213.75, 0.0, -41.162]
  - [-213.75, 135.0, -41.162]
  - [213.75, 135.0, -41.162]
  - [-213.4, -175.0, -33.542]
  - [213.4, -175.0, -33.542]
  - [-213.4, -95.0, -33.542]
  - [213.4, -95.0, -33.542]
  - [-213.4, -40.0, -33.542]
  - [213.4, -40.0, -33.542]
  - [-213.4, 40.0, -33.542]
  - [213.4, 40.0, -33.542]
  - [-213.4, 95.0, -33.542]
  - [213.4, 95.0, -33.542]
  - [-213.4, 175.0, -33.542]
  - [213.4, 175.0, -33.542]
  - [-213.75, -135.0, -25.922]
  - [213.75, -135.0, -25.922]
  - [-213.75, 0.0, -25.922]
  - [213.75, 0.0, -25.922]
  - [-213.75, 135.0, -25.922]
  - [213.75, 135.0, -25.922]
  - [-213.75, -135.0, 25.922]
  - [213.75, -135.0, 25.922]
  - [-213.75, 0.0, 25.922]
  - [213.75, 0.0, 25.922]
  - [-213.75, 135.0, 25.922]
  - [213.75, 135.0, 25.922]
  - [-213.4, -175.0, 33.542]
  - [213.4, -175.0, 33.542]
  - [-213.4, -95.0, 33.542]
  - [213.4, -95.0, 33.542]
  - [-213.4, -40.0, 33.542]
  - [213.4, -40.0, 33.542]
  - [-213.4, 40.0, 33.542]
  - [213.4, 40.0, 33.542]
  - [-213.4, 95.0, 33.542]
  - [213.4, 95.0, 33.542]
  - [-213.4, 175.0, 33.542]
  - [213.4, 175.0, 33.542]
  - [-213.75, -135.0, 41.162]
  - [213.75, -135.0, 41.162]
  - [-213.75, 0.0, 41.162]
  - [213.75, 0.0, 41.162]
  - [-213.75, 135.0, 41.162]
  - [213.75, 135.0, 41.162]
  - [-213.75, -175.0, 55.922]
  - [213.75, -175.0, 55.922]
  - [-213.75, -95.0, 55.922]
  - [213.75, -95.0, 55.922]
  - [-213.75, -40.0, 55.922]
  - [213.75, -40.0, 55.922]
  - [-213.75, 40.0, 55.922]
  - [213.75, 40.0, 55.922]
  - [-213.75, 95.0, 55.922]
  - [213.75, 95.0, 55.922]
  - [-213.75, 175.0, 55.922]
  - [213.75, 175.0, 55.922]
  - [-213.4, -135.0, 63.542]
  - [213.4, -135.0, 63.542]
  - [-213.4, 0.0, 63.542]
  - [213.4, 0.0, 63.542]
  - [-213.4, 135.0, 63.542]
  - [213.4, 135.0, 63.542]
  - [-213.75, -175.0, 71.162]
  - [213.75, -175.0, 71.162]
  - [-213.75, -95.0, 71.162]
  - [213.75, -95.0, 71.162]
  - [-213.75, -40.0, 71.162]
  - [213.75, -40.0, 71.162]
  - [-213.75, 40.0, 71.162]
  - [213.75, 40.0, 71.162]
  - [-213.75, 95.0, 71.162]
  - [213.75, 95.0, 71.162]
  - [-213.75, 175.0, 71.162]
  - [213.75, 175.0, 71.162]
  - [-213.75, -135.0, 85.922]
  - [213.75, -135.0, 85.922]
  - [-213.75, 0.0, 85.922]
  - [213.75, 0.0, 85.922]
  - [-213.75, 135.0, 85.922]
  - [213.75, 135.0, 85.922]
  - [-213.4, -175.0, 93.542]
  - [213.4, -175.0, 93.542]
  - [-213.4, -95.0, 93.542]
  - [213.4, -95.0, 93.542]
  - [-213.4, -40.0, 93.542]
  - [213.4, -40.0, 93.542]
  - [-213.4, 40.0, 93.542]
  - [213.4, 40.0, 93.542]
  - [-213.4, 95.0, 93.542]
  - [213.4, 95.0, 93.542]
  - [-213.4, 175.0, 93.542]
  - [213.4, 175.0, 93.542]
  - [-213.75, -135.0, 101.162]
  - [213.75, -135.0, 101.162]
  - [-213.75, 0.0, 101.162]
  - [213.75, 0.0, 101.162]
  - [-213.75, 135.0, 101.162]
  - [213.75, 135.0, 101.162]
  - [-213.75, -135.0, 159.206]
  - [213.75, -135.0, 159.206]
  - [-213.75, 0.0, 159.206]
  - [213.75, 0.0, 159.206]
  - [-213.75, 135.0, 159.206]
  - [213.75, 135.0, 159.206]
  - [-213.4, -175.0, 166.826]
  - [213.4, -175.0, 166.826]
  - [-213.4, -95.0, 166.826]
  - [213.4, -95.0, 166.826]
  - [-213.4, -40.0, 166.826]
  - [213.4, -40.0, 166.826]
  - [-213.4, 40.0, 166.826]
  - [213.4, 40.0, 166.826]
  - [-213.4, 95.0, 166.826]
  - [213.4, 95.0, 166.826]
  - [-213.4, 175.0, 166.826]
  - [213.4, 175.0, 166.826]
  - [-213.75, -135.0, 174.446]
  - [213.75, -135.0, 174.446]
  - [-213.75, 0.0, 174.446]
  - [213.75, 0.0, 174.446]
  - [-213.75, 135.0, 174.446]
  - [213.75, 135.0, 174.446]
  - [-213.75, -175.0, 189.206]
  - [213.75, -175.0, 189.206]
  - [-213.75, -95.0, 189.206]
  - [213.75, -95.0, 189.206]
  - [-213.75, -40.0, 189.206]
  - [213.75, -40.0, 189.206]
  - [-213.75, 40.0, 189.206]
  - [213.75, 40.0, 189.206]
  - [-213.75, 95.0, 189.206]
  - [213.75, 95.0, 189.206]
  - [-213.75, 175.0, 189.206]
  - [213.75, 175.0, 189.206]
  - [-213.4, -135.0, 196.826]
  - [213.4, -135.0, 196.826]
  - [-213.4, 0.0, 196.826]
  - [213.4, 0.0, 196.826]
  - [-213.4, 135.0, 196.826]
  - [213.4, 135.0, 196.826]
  - [-213.75, -175.0, 204.446]
  - [213.75, -175.0, 204.446]
  - [-213.75, -95.0, 204.446]
  - [213.75, -95.0, 204.446]
  - [-213.75, -40.0, 204.446]
  - [213.75, -40.0, 204.446]
  - [-213.75, 40.0, 204.446]
  - [213.75, 40.0, 204.446]
  - [-213.75, 95.0, 204.446]
  - [213.75, 95.0, 204.446]
  - [-213.75, 175.0, 204.446]
  - [213.75, 175.0, 204.446]
  - [-213.75, -135.0, 219.206]
  - [213.75, -135.0, 219.206]
  - [-213.75, 0.0, 219.206]
  - [213.75, 0.0, 219.206]
  - [-213.75, 135.0, 219.206]
  - [213.75, 135.0, 219.206]
  - [-213.4, -175.0, 226.826]
  - [213.4, -175.0, 226.826]
  - [-213.4, -95.0, 226.826]
  - [213.4, -95.0, 226.826]
  - [-213.4, -40.0, 226.826]
  - [213.4, -40.0, 226.826]
  - [-213.4, 40.0, 226.826]
  - [213.4, 40.0, 226.826]
  - [-213.4, 95.0, 226.826]
  - [213.4, 95.0, 226.826]
  - [-213.4, 175.0, 226.826]
  - [213.4, 175.0, 226.826]
  - [-213.75, -135.0, 234.446]
  - [213.75, -135.0, 234.446]
  - [-213.75, 0.0, 234.446]
  - [213.75, 0.0, 234.446]
  - [-213.75, 135.0, 234.446]
  - [213.75, 135.0, 234.446]
crt:
  normals: [1, 1, 1, 2, 2, 0, 0]
  dimensions:
  - [899.2, 4.6, 899.2]
  - [899.2, 4.6, 899.2]
  - [809.0, 2.6, 987.0]
  - [719.2, 719.2, 2.8]
  - [719.2, 719.25, 22.4]
  - [2.8, 719.2, 899.2]
  - [2.8, 719.2, 899.2]
  positions:
  - [0.21, 764.05, 290.17]
  - [0.47, 623.7, 277.23]
  - [-1.48, -381.3, 293.88]
  - [-5.27, 33.03, -195.45]
  - [-0.31, 11.465, 787.35]
  - [-402.6, 37.21, 293.9]
  - [402.8, 34.66, 295.07]
