name: DUNE10kt-1x2x6
tag: dune10kt_v4_1x2x6
version: 6
gdml: dune10kt_v4_1x2x6.gdml
tpc:
  dimensions: [359.4149, 1198.409, 1391.4021]
  module_ids: [0, 0]
  positions:
  - [-183.6685, 0.0, 696.2919]
  - [183.6685, 0.0, 696.2919]
  det_ids: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
optical:
  volume: module
  global_index: true
  shape: box
  dimensions: [2.2, 9.3, 46.8]
  positions:
  - [0.05, 591.569, 661.1781]
  - [0.05, 529.298, 661.1781]
  - [0.05, 467.028, 661.1781]
  - [0.05, 404.758, 661.1781]
  - [0.05, 342.487, 661.1781]
  - [0.05, 280.217, 661.1781]
  - [0.05, 217.946, 661.1781]
  - [0.05, 155.676, 661.1781]
  - [0.05, 93.4056, 661.1781]
  - [0.05, 31.1352, 661.1781]
  - [0.05, 591.569, 612.3781]
  - [0.05, 529.298, 612.3781]
  - [0.05, 467.028, 612.3781]
  - [0.05, 404.758, 612.3781]
  - [0.05, 342.487, 612.3781]
  - [0.05, 280.217, 612.3781]
  - [0.05, 217.946, 612.3781]
  - [0.05, 155.676, 612.3781]
  - [0.05, 93.4056, 612.3781]
  - [0.05, 31.1352, 612.3781]
  - [0.05, 591.569, 549.5781]
  - [0.05, 529.298, 549.5781]
  - [0.05, 467.028, 549.5781]
  - [0.05, 404.758, 549.5781]
  - [0.05, 342.487, 549.5781]
  - [0.05, 280.217, 549.5781]
  - [0.05, 217.946, 549.5781]
  - [0.05, 155.676, 549.5781]
  - [0.05, 93.4056, 549.5781]
  - [0.05, 31.1352, 549.5781]
  - [0.05, 591.569, 500.7781]
  - [0.05, 529.298, 500.7781]
  - [0.05, 467.028, 500.7781]
  - [0.05, 404.758, 500.7781]
  - [0.05, 342.487, 500.7781]
  - [0.05, 280.217, 500.7781]
  - [0.05, 217.946, 500.7781]
  - [0.05, 155.676, 500.7781]
  - [0.05, 93.4056, 500.7781]
  - [0.05, 31.1352, 500.7781]
  - [0.05, 591.569, 428.7881]
  - [0.05, 529.298, 428.7881]
  - [0.05, 467.028, 428.7881]
  - [0.05, 404.758, 428.7881]
  - [0.05, 342.487, 428.7881]
  - [0.05, 280.217, 428.7881]
  - [0.05, 217.946, 428.7881]
  - [0.05, 155.676, 428.7881]
  - [0.05, 93.4056, 428.7881]
  - [0.05, 31.1352, 428.7881]
  - [0.05, 591.569, 379.9881]
  - [0.05, 529.298, 379.9881]
  - [0.05, 467.028, 379.9881]
  - [0.05, 404.758, 379.9881]
  - [0.05, 342.487, 379.9881]
  - [0.05, 280.217, 379.9881]
  - [0.05, 217.946, 379.9881]
  - [0.05, 155.676, 379.9881]
  - [0.05, 93.4056, 379.9881]
  - [0.05, 31.1352, 379.9881]
  - [0.05, 591.569, 317.1881]
  - [0.05, 529.298, 317.1881]
  - [0.05, 467.028, 317.1881]
  - [0.05, 404.758, 317.1881]
  - [0.05, 342.487, 317.1881]
  - [0.05, 280.217, 317.1881]
  - [0.05, 217.946, 317.1881]
  - [0.05, 155.676, 317.1881]
  - [0.05, 93.4056, 317.1881]
  - [0.05, 31.1352, 317.1881]
  - [0.05, 591.569, 268.3871]
  - [0.05, 529.298, 268.3871]
  - [0.05, 467.028, 268.3871]
  - [0.05, 404.758, 268.3871]
  - [0.05, 342.487, 268.3871]
  - [0.05, 280.217, 268.3871]
  - [0.05, 217.946, 268.3871]
  - [0.05, 155.676, 268.3871]
  - [0.05, 93.4056, 268.3871]
  - [0.05, 31.1352, 268.3871]
  - [0.05, 591.569, 196.3971]
  - [0.05, 529.298, 196.3971]
  - [0.05, 467.028, 196.3971]
  - [0.05, 404.758, 196.3971]
  - [0.05, 342.487, 196.3971]
  - [0.05, 280.217, 196.3971]
  - [0.05, 217.946, 196.3971]
  - [0.05, 155.676, 196.3971]
  - [0.05, 93.4056, 196.3971]
  - [0.05, 31.1352, 196.3971]
  - [0.05, 591.569, 147.5971]
  - [0.05, 529.298, 147.5971]
  - [0.05, 467.028, 147.5971]
  - [0.05, 404.758, 147.5971]
  - [0.05, 342.487, 147.5971]
  - [0.05, 280.217, 147.5971]
  - [0.05, 217.946, 147.5971]
  - [0.05, 155.676, 147.5971]
  - [0.05, 93.4056, 147.5971]
  - [0.05, 31.1352, 147.5971]
  - [0.05, 591.569, 84.7971]
  - [0.05, 529.298, 84.7971]
  - [0.05, 467.028, 84.7971]
  - [0.05, 404.758, 84.7971]
  - [0.05, 342.487, 84.7971]
  - [0.05, 280.217, 84.7971]
  - [0.05, 217.946, 84.7971]
  - [0.05, 155.676, 84.7971]
  - [0.05, 93.4056, 84.7971]
  - [0.05, 31.1352, 84.7971]
  - [0.05, 591.569, 35.9971]
  - [0.05, 529.298, 35.9971]
  - [0.05, 467.028, 35.9971]
  - [0.05, 404.758, 35.9971]
  - [0.05, 342.487, 35.9971]
  - [0.05, 280.217, 35.9971]
  - [0.05, 217.946, 35.9971]
  - [0.05, 155.676, 35.9971]
  - [0.05, 93.4056, 35.9971]
  - [0.05, 31.1352, 35.9971]
  - [0.05, 591.569, -35.9929]
  - [0.05, 529.298, -35.9929]
  - [0.05, 467.028, -35.9929]
  - [0.05, 404.758, -35.9929]
  - [0.05, 342.487, -35.9929]
  - [0.05, 280.217, -35.9929]
  - [0.05, 217.946, -35.9929]
  - [0.05, 155.676, -35.9929]
  - [0.05, 93.4056, -35.9929]
  - [0.05, 31.1352, -35.9929]
  - [0.05, 591.569, -84.7929]
  - [0.05, 529.298, -84.7929]
  - [0.05, 467.028, -84.7929]
  - [0.05, 404.758, -84.7929]
  - [0.05, 342.487, -84.7929]
  - [0.05, 280.217, -84.7929]
  - [0.05, 217.946, -84.7929]
  - [0.05, 155.676, -84.7929]
  - [0.05, 93.4056, -84.7929]
  - [0.05, 31.1352, -84.7929]
  - [0.05, 591.569, -147.5929]
  - [0.05, 529.298, -147.5929]
  - [0.05, 467.028, -147.5929]
  - [0.05, 404.758, -147.5929]
  - [0.05, 342.487, -147.5929]
  - [0.05, 280.217, -147.5929]
  - [0.05, 217.946, -147.5929]
  - [0.05, 155.676, -147.5929]
  - [0.05, 93.4056, -147.5929]
  - [0.05, 31.1352, -147.5929]
  - [0.05, 591.569, -196.3929]
  - [0.05, 529.298, -196.3929]
  - [0.05, 467.028, -196.3929]
  - [0.05, 404.758, -196.3929]
  - [0.05, 342.487, -196.3929]
  - [0.05, 280.217, -196.3929]
  - [0.05, 217.946, -196.3929]
  - [0.05, 155.676, -196.3929]
  - [0.05, 93.4056, -196.3929]
  - [0.05, 31.1352, -196.3929]
  - [0.05, 591.569, -268.3829]
  - [0.05, 529.298, -268.3829]
  - [0.05, 467.028, -268.3829]
  - [0.05, 404.758, -268.3829]
  - [0.05, 342.487, -268.3829]
  - [0.05, 280.217, -268.3829]
  - [0.05, 217.946, -268.3829]
  - [0.05, 155.676, -268.3829]
  - [0.05, 93.4056, -268.3829]
  - [0.05, 31.1352, -268.3829]
  - [0.05, 591.569, -317.1829]
  - [0.05, 529.298, -317.1829]
  - [0.05, 467.028, -317.1829]
  - [0.05, 404.758, -317.1829]
  - [0.05, 342.487, -317.1829]
  - [0.05, 280.217, -317.1829]
  - [0.05, 217.946, -317.1829]
  - [0.05, 155.676, -317.1829]
  - [0.05, 93.4056, -317.1829]
  - [0.05, 31.1352, -317.1829]
  - [0.05, 591.569, -379.9829]
  - [0.05, 529.298, -379.9829]
  - [0.05, 467.028, -379.9829]
  - [0.05, 404.758, -379.9829]
  - [0.05, 342.487, -379.9829]
  - [0.05, 280.217, -379.9829]
  - [0.05, 217.946, -379.9829]
  - [0.05, 155.676, -379.9829]
  - [0.05, 93.4056, -379.9829]
  - [0.05, 31.1352, -379.9829]
  - [0.05, 591.569, -428.7829]
  - [0.05, 529.298, -428.7829]
  - [0.05, 467.028, -428.7829]
  - [0.05, 404.758, -428.7829]
  - [0.05, 342.487, -428.7829]
  - [0.05, 280.217, -428.7829]
  - [0.05, 217.946, -428.7829]
  - [0.05, 155.676, -428.7829]
  - [0.05, 93.4056, -428.7829]
  - [0.05, 31.1352, -428.7829]
  - [0.05, 591.569, -500.7729]
  - [0.05, 529.298, -500.7729]
  - [0.05, 467.028, -500.7729]
  - [0.05, 404.758, -500.7729]
  - [0.05, 342.487, -500.7729]
  - [0.05, 280.217, -500.7729]
  - [0.05, 217.946, -500.7729]
  - [0.05, 155.676, -500.7729]
  - [0.05, 93.4056, -500.7729]
  - [0.05, 31.1352, -500.7729]
  - [0.05, 591.569, -549.5729]
  - [0.05, 529.298, -549.5729]
  - [0.05, 467.028, -549.5729]
  - [0.05, 404.758, -549.5729]
  - [0.05, 342.487, -549.5729]
  - [0.05, 280.217, -549.5729]
  - [0.05, 217.946, -549.5729]
  - [0.05, 155.676, -549.5729]
  - [0.05, 93.4056, -549.5729]
  - [0.05, 31.1352, -549.5729]
  - [0.05, 591.569, -612.3731]
  - [0.05, 529.298, -612.3731]
  - [0.05, 467.028, -612.3731]
  - [0.05, 404.758, -612.3731]
  - [0.05, 342.487, -612.3731]
  - [0.05, 280.217, -612.3731]
  - [0.05, 217.946, -612.3731]
  - [0.05, 155.676, -612.3731]
  - [0.05, 93.4056, -612.3731]
  - [0.05, 31.1352, -612.3731]
  - [0.05, 591.569, -661.1731]
  - [0.05, 529.298, -661.1731]
  - [0.05, 467.028, -661.1731]
  - [0.05, 404.758, -661.1731]
  - [0.05, 342.487, -661.1731]
  - [0.05, 280.217, -661.1731]
  - [0.05, 217.946, -661.1731]
  - [0.05, 155.676, -661.1731]
  - [0.05, 93.4056, -661.1731]
  - [0.05, 31.1352, -661.1731]
  - [-0.05, -31.1352, 661.1781]
  - [-0.05, -93.4056, 661.1781]
  - [-0.05, -155.676, 661.1781]
  - [-0.05, -217.946, 661.1781]
  - [-0.05, -280.217, 661.1781]
  - [-0.05, -342.487, 661.1781]
  - [-0.05, -404.758, 661.1781]
  - [-0.05, -467.028, 661.1781]
  - [-0.05, -529.298, 661.1781]
  - [-0.05, -591.569, 661.1781]
  - [-0.05, -31.1352, 612.3781]
  - [-0.05, -93.4056, 612.3781]
  - [-0.05, -155.676, 612.3781]
  - [-0.05, -217.946, 612.3781]
  - [-0.05, -280.217, 612.3781]
  - [-0.05, -342.487, 612.3781]
  - [-0.05, -404.758, 612.3781]
  - [-0.05, -467.028, 612.3781]
  - [-0.05, -529.298, 612.3781]
  - [-0.05, -591.569, 612.3781]
  - [-0.05, -31.1352, 549.5781]
  - [-0.05, -93.4056, 549.5781]
  - [-0.05, -155.676, 549.5781]
  - [-0.05, -217.946, 549.5781]
  - [-0.05, -280.217, 549.5781]
  - [-0.05, -342.487, 549.5781]
  - [-0.05, -404.758, 549.5781]
  - [-0.05, -467.028, 549.5781]
  - [-0.05, -529.298, 549.5781]
  - [-0.05, -591.569, 549.5781]
  - [-0.05, -31.1352, 500.7781]
  - [-0.05, -93.4056, 500.7781]
  - [-0.05, -155.676, 500.7781]
  - [-0.05, -217.946, 500.7781]
  - [-0.05, -280.217, 500.7781]
  - [-0.05, -342.487, 500.7781]
  - [-0.05, -404.758, 500.7781]
  - [-0.05, -467.028, 500.7781]
  - [-0.05, -529.298, 500.7781]
  - [-0.05, -591.569, 500.7781]
  - [-0.05, -31.1352, 428.7881]
  - [-0.05, -93.4056, 428.7881]
  - [-0.05, -155.676, 428.7881]
  - [-0.05, -217.946, 428.7881]
  - [-0.05, -280.217, 428.7881]
  - [-0.05, -342.487, 428.7881]
  - [-0.05, -404.758, 428.7881]
  - [-0.05, -467.028, 428.7881]
  - [-0.05, -529.298, 428.7881]
  - [-0.05, -591.569, 428.7881]
  - [-0.05, -31.1352, 379.9881]
  - [-0.05, -93.4056, 379.9881]
  - [-0.05, -155.676, 379.9881]
  - [-0.05, -217.946, 379.9881]
  - [-0.05, -280.217, 379.9881]
  - [-0.05, -342.487, 379.9881]
  - [-0.05, -404.758, 379.9881]
  - [-0.05, -467.028, 379.9881]
  - [-0.05, -529.298, 379.9881]
  - [-0.05, -591.569, 379.9881]
  - [-0.05, -31.1352, 317.1881]
  - [-0.05, -93.4056, 317.1881]
  - [-0.05, -155.676, 317.1881]
  - [-0.05, -217.946, 317.1881]
  - [-0.05, -280.217, 317.1881]
  - [-0.05, -342.487, 317.1881]
  - [-0.05, -404.758, 317.1881]
  - [-0.05, -467.028, 317.1881]
  - [-0.05, -529.298, 317.1881]
  - [-0.05, -591.569, 317.1881]
  - [-0.05, -31.1352, 268.3871]
  - [-0.05, -93.4056, 268.3871]
  - [-0.05, -155.676, 268.3871]
  - [-0.05, -217.946, 268.3871]
  - [-0.05, -280.217, 268.3871]
  - [-0.05, -342.487, 268.3871]
  - [-0.05, -404.758, 268.3871]
  - [-0.05, -467.028, 268.3871]
  - [-0.05, -529.298, 268.3871]
  - [-0.05, -591.569, 268.3871]
  - [-0.05, -31.1352, 196.3971]
  - [-0.05, -93.4056, 196.3971]
  - [-0.05, -155.676, 196.3971]
  - [-0.05, -217.946, 196.3971]
  - [-0.05, -280.217, 196.3971]
  - [-0.05, -342.487, 196.3971]
  - [-0.05, -404.758, 196.3971]
  - [-0.05, -467.028, 196.3971]
  - [-0.05, -529.298, 196.3971]
  - [-0.05, -591.569, 196.3971]
  - [-0.05, -31.1352, 147.5971]
  - [-0.05, -93.4056, 147.5971]
  - [-0.05, -155.676, 147.5971]
  - [-0.05, -217.946, 147.5971]
  - [-0.05, -280.217, 147.5971]
  - [-0.05, -342.487, 147.5971]
  - [-0.05, -404.758, 147.5971]
  - [-0.05, -467.028, 147.5971]
  - [-0.05, -529.298, 147.5971]
  - [-0.05, -591.569, 147.5971]
  - [-0.05, -31.1352, 84.7971]
  - [-0.05, -93.4056, 84.7971]
  - [-0.05, -155.676, 84.7971]
  - [-0.05, -217.946, 84.7971]
  - [-0.05, -280.217, 84.7971]
  - [-0.05, -342.487, 84.7971]
  - [-0.05, -404.758, 84.7971]
  - [-0.05, -467.028, 84.7971]
  - [-0.05, -529.298, 84.7971]
  - [-0.05, -591.569, 84.7971]
  - [-0.05, -31.1352, 35.9971]
  - [-0.05, -93.4056, 35.9971]
  - [-0.05, -155.676, 35.9971]
  - [-0.05, -217.946, 35.9971]
  - [-0.05, -280.217, 35.9971]
  - [-0.05, -342.487, 35.9971]
  - [-0.05, -404.758, 35.9971]
  - [-0.05, -467.028, 35.9971]
  - [-0.05, -529.298, 35.9971]
  - [-0.05, -591.569, 35.9971]
  - [-0.05, -31.1352, -35.9929]
  - [-0.05, -93.4056, -35.9929]
  - [-0.05, -155.676, -35.9929]
  - [-0.05, -217.946, -35.9929]
  - [-0.05, -280.217, -35.9929]
  - [-0.05, -342.487, -35.9929]
  - [-0.05, -404.758, -35.9929]
  - [-0.05, -467.028, -35.9929]
  - [-0.05, -529.298, -35.9929]
  - [-0.05, -591.569, -35.9929]
  - [-0.05, -31.1352, -84.7929]
  - [-0.05, -93.4056, -84.7929]
  - [-0.05, -155.676, -84.7929]
  - [-0.05, -217.946, -84.7929]
  - [-0.05, -280.217, -84.7929]
  - [-0.05, -342.487, -84.7929]
  - [-0.05, -404.758, -84.7929]
  - [-0.05, -467.028, -84.7929]
  - [-0.05, -529.298, -84.7929]
  - [-0.05, -591.569, -84.7929]
  - [-0.05, -31.1352, -147.5929]
  - [-0.05, -93.4056, -147.5929]
  - [-0.05, -155.676, -147.5929]
  - [-0.05, -217.946, -147.5929]
  - [-0.05, -280.217, -147.5929]
  - [-0.05, -342.487, -147.5929]
  - [-0.05, -404.758, -147.5929]
  - [-0.05, -467.028, -147.5929]
  - [-0.05, -529.298, -147.5929]
  - [-0.05, -591.569, -147.5929]
  - [-0.05, -31.1352, -196.3929]
  - [-0.05, -93.4056, -196.3929]
  - [-0.05, -155.676, -196.3929]
  - [-0.05, -217.946, -196.3929]
  - [-0.05, -280.217, -196.3929]
  - [-0.05, -342.487, -196.3929]
  - [-0.05, -404.758, -196.3929]
  - [-0.05, -467.028, -196.3929]
  - [-0.05, -529.298, -196.3929]
  - [-0.05, -591.569, -196.3929]
  - [-0.05, -31.1352, -268.3829]
  - [-0.05, -93.4056, -268.3829]
  - [-0.05, -155.676, -268.3829]
  - [-0.05, -217.946, -268.3829]
  - [-0.05, -280.217, -268.3829]
  - [-0.05, -342.487, -268.3829]
  - [-0.05, -404.758, -268.3829]
  - [-0.05, -467.028, -268.3829]
  - [-0.05, -529.298, -268.3829]
  - [-0.05, -591.569, -268.3829]
  - [-0.05, -31.1352, -317.1829]
  - [-0.05, -93.4056, -317.1829]
  - [-0.05, -155.676, -317.1829]
  - [-0.05, -217.946, -317.1829]
  - [-0.05, -280.217, -317.1829]
  - [-0.05, -342.487, -317.1829]
  - [-0.05, -404.758, -317.1829]
  - [-0.05, -467.028, -317.1829]
  - [-0.05, -529.298, -317.1829]
  - [-0.05, -591.569, -317.1829]
  - [-0.05, -31.1352, -379.9829]
  - [-0.05, -93.4056, -379.9829]
  - [-0.05, -155.676, -379.9829]
  - [-0.05, -217.946, -379.9829]
  - [-0.05, -280.217, -379.9829]
  - [-0.05, -342.487, -379.9829]
  - [-0.05, -404.758, -379.9829]
  - [-0.05, -467.028, -379.9829]
  - [-0.05, -529.298, -379.9829]
  - [-0.05, -591.569, -379.9829]
  - [-0.05, -31.1352, -428.7829]
  - [-0.05, -93.4056, -428.7829]
  - [-0.05, -155.676, -428.7829]
  - [-0.05, -217.946, -428.7829]
  - [-0.05, -280.217, -428.7829]
  - [-0.05, -342.487, -428.7829]
  - [-0.05, -404.758, -428.7829]
  - [-0.05, -467.028, -428.7829]
  - [-0.05, -529.298, -428.7829]
  - [-0.05, -591.569, -428.7829]
  - [-0.05, -31.1352, -500.7729]
  - [-0.05, -93.4056, -500.7729]
  - [-0.05, -155.676, -500.7729]
  - [-0.05, -217.946, -500.7729]
  - [-0.05, -280.217, -500.7729]
  - [-0.05, -342.487, -500.7729]
  - [-0.05, -404.758, -500.7729]
  - [-0.05, -467.028, -500.7729]
  - [-0.05, -529.298, -500.7729]
  - [-0.05, -591.569, -500.7729]
  - [-0.05, -31.1352, -549.5729]
  - [-0.05, -93.4056, -549.5729]
  - [-0.05, -155.676, -549.5729]
  - [-0.05, -217.946, -549.5729]
  - [-0.05, -280.217, -549.5729]
  - [-0.05, -342.487, -549.5729]
  - [-0.05, -404.758, -549.5729]
  - [-0.05, -467.028, -549.5729]
  - [-0.05, -529.298, -549.5729]
  - [-0.05, -591.569, -549.5729]
  - [-0.05, -31.1352, -612.3731]
  - [-0.05, -93.4056, -612.3731]
  - [-0.05, -155.676, -612.3731]
  - [-0.05, -217.946, -612.3731]
  - [-0.05, -280.217, -612.3731]
  - [-0.05, -342.487, -612.3731]
  - [-0.05, -404.758, -612.3731]
  - [-0.05, -467.028, -612.3731]
  - [-0.05, -529.298, -612.3731]
  - [-0.05, -591.569, -612.3731]
  - [-0.05, -31.1352, -661.1731]
  - [-0.05, -93.4056, -661.1731]
  - [-0.05, -155.676, -661.1731]
  - [-0.05, -217.946, -661.1731]
  - [-0.05, -280.217, -661.1731]
  - [-0.05, -342.487, -661.1731]
  - [-0.05, -404.758, -661.1731]
  - [-0.05, -467.028, -661.1731]
  - [-0.05, -529.298, -661.1731]
  - [-0.05, -591.569, -661.1731]
