name: FSD
tag: cr1
version: 1
crs_files: [data/fsd_flow/multi_tile_layout-3.0.40_NDLArModule_v3.yaml]
lrs_file: data/fsd_flow/light_module_desc-6.0.0.yaml
tpc:
  dimensions: [46.788, 297.6, 95.232]
  module_ids: [0, 0]
  positions:
  - [23.7115, 0.0, 0.0]
  - [-23.7115, 0.0, 0.0]
optical:
  volume: tpc
  shape: [box, box]
  mirror: true
  dimensions:
  - [48.0, 31.02, 1.0]
  - [48.0, 10.34, 1.0]
  shape_ids: [1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
    0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0]
  det_ids: [0, 0, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7, 7, 7, 7,
    8, 8, 9, 9, 10, 10, 11, 11, 11, 11, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15,
    15, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 21, 21, 22,
    22, 23, 23, 23, 23, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27, 27, 27, 27, 27, 28,
    28, 29, 29, 30, 30, 31, 31, 31, 31, 31, 31, 32, 32, 33, 33, 34, 34, 35, 35, 35,
    35, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 39, 39, 39, 39]
  positions:
  - [0, -149.93, -49.0]
  - [0, -139.59, -49.0]
  - [0, -129.25, -49.0]
  - [0, -108.57, -49.0]
  - [0, -87.89, -49.0]
  - [0, -77.55, -49.0]
  - [0, -67.21, -49.0]
  - [0, -46.53, -49.0]
  - [0, -25.85, -49.0]
  - [0, -15.51, -49.0]
  - [0, -5.17, -49.0]
  - [0, 15.51, -49.0]
  - [0, 36.19, -49.0]
  - [0, 46.53, -49.0]
  - [0, 56.87, -49.0]
  - [0, 77.55, -49.0]
  - [0, 98.23, -49.0]
  - [0, 108.57, -49.0]
  - [0, 118.91, -49.0]
  - [0, 139.59, -49.0]
  - [0, -149.93, 49.0]
  - [0, -139.59, 49.0]
  - [0, -129.25, 49.0]
  - [0, -108.57, 49.0]
  - [0, -87.89, 49.0]
  - [0, -77.55, 49.0]
  - [0, -67.21, 49.0]
  - [0, -46.53, 49.0]
  - [0, -25.85, 49.0]
  - [0, -15.51, 49.0]
  - [0, -5.17, 49.0]
  - [0, 15.51, 49.0]
  - [0, 36.19, 49.0]
  - [0, 46.53, 49.0]
  - [0, 56.87, 49.0]
  - [0, 77.55, 49.0]
  - [0, 98.23, 49.0]
  - [0, 108.57, 49.0]
  - [0, 118.91, 49.0]
  - [0, 139.59, 49.0]
