name: ICARUS
tag: icarus_v4
version: 4
gdml: icarus_refactored_nounderscore_20230918.gdml
tpc:
  dimensions: [148.2, 316.82, 1789.902]
  module_ids: [0, 0, 1, 1]
  positions:
  - [-284.39, -23.45, 0.0]
  - [-136.04, -23.45, 0.0]
  - [136.04, -23.45, 0.0]
  - [284.39, -23.45, 0.0]
  det_ids: [0, 0, 1, 1]
  limits:
    intercepts:
    - [0., 1650.6114, 0.]
    - [0., 1650.6114, 0.]
    - [0., -1697.5114, 0.]
    - [0., -1697.5114, 0.]
    norms:
    - [0., 0.5, -0.866025]
    - [0., 0.5, 0.866025]
    - [0., -0.5, -0.866025]
    - [0., -0.5, 0.866025]
optical:
  volume: module
  global_index: false
  shape: ellipsoid
  dimensions: [10.1601, 20.32, 20.32]
  positions:
  - [-160.855, -52.8, -872.9]
  - [-160.855, 52.8, -872.9]
  - [-160.855, -105.6, -823.02]
  - [-160.855, 0.0, -823.02]
  - [-160.855, 105.6, -823.02]
  - [-160.855, -105.6, -773.14]
  - [-160.855, 0.0, -773.14]
  - [-160.855, 105.6, -773.14]
  - [-160.855, -52.8, -723.26]
  - [-160.855, 52.8, -723.26]
  - [-160.855, -52.8, -673.38]
  - [-160.855, 52.8, -673.38]
  - [-160.855, -105.6, -623.5]
  - [-160.855, 0.0, -623.5]
  - [-160.855, 105.6, -623.5]
  - [-160.855, -105.6, -573.62]
  - [-160.855, 0.0, -573.62]
  - [-160.855, 105.6, -573.62]
  - [-160.855, -52.8, -523.74]
  - [-160.855, 52.8, -523.74]
  - [-160.855, -52.8, -473.86]
  - [-160.855, 52.8, -473.86]
  - [-160.855, -105.6, -423.98]
  - [-160.855, 0.0, -423.98]
  - [-160.855, 105.6, -423.98]
  - [-160.855, -105.6, -374.1]
  - [-160.855, 0.0, -374.1]
  - [-160.855, 105.6, -374.1]
  - [-160.855, -52.8, -324.22]
  - [-160.855, 52.8, -324.22]
  - [-160.855, -52.8, -274.34]
  - [-160.855, 52.8, -274.34]
  - [-160.855, -105.6, -224.46]
  - [-160.855, 0.0, -224.46]
  - [-160.855, 105.6, -224.46]
  - [-160.855, -105.6, -174.58]
  - [-160.855, 0.0, -174.58]
  - [-160.855, 105.6, -174.58]
  - [-160.855, -52.8, -124.7]
  - [-160.855, 52.8, -124.7]
  - [-160.855, -52.8, -74.82]
  - [-160.855, 52.8, -74.82]
  - [-160.855, -105.6, -24.94]
  - [-160.855, 0.0, -24.94]
  - [-160.855, 105.6, -24.94]
  - [-160.855, -105.6, 24.94]
  - [-160.855, 0.0, 24.94]
  - [-160.855, 105.6, 24.94]
  - [-160.855, -52.8, 74.82]
  - [-160.855, 52.8, 74.82]
  - [-160.855, -52.8, 124.7]
  - [-160.855, 52.8, 124.7]
  - [-160.855, -105.6, 174.58]
  - [-160.855, 0.0, 174.58]
  - [-160.855, 105.6, 174.58]
  - [-160.855, -105.6, 224.46]
  - [-160.855, 0.0, 224.46]
  - [-160.855, 105.6, 224.46]
  - [-160.855, -52.8, 274.34]
  - [-160.855, 52.8, 274.34]
  - [-160.855, -52.8, 324.22]
  - [-160.855, 52.8, 324.22]
  - [-160.855, -105.6, 374.1]
  - [-160.855, 0.0, 374.1]
  - [-160.855, 105.6, 374.1]
  - [-160.855, -105.6, 423.98]
  - [-160.855, 0.0, 423.98]
  - [-160.855, 105.6, 423.98]
  - [-160.855, -52.8, 473.86]
  - [-160.855, 52.8, 473.86]
  - [-160.855, -52.8, 523.74]
  - [-160.855, 52.8, 523.74]
  - [-160.855, -105.6, 573.62]
  - [-160.855, 0.0, 573.62]
  - [-160.855, 105.6, 573.62]
  - [-160.855, -105.6, 623.5]
  - [-160.855, 0.0, 623.5]
  - [-160.855, 105.6, 623.5]
  - [-160.855, -52.8, 673.38]
  - [-160.855, 52.8, 673.38]
  - [-160.855, -52.8, 723.26]
  - [-160.855, 52.8, 723.26]
  - [-160.855, -105.6, 773.14]
  - [-160.855, 0.0, 773.14]
  - [-160.855, 105.6, 773.14]
  - [-160.855, -105.6, 823.02]
  - [-160.855, 0.0, 823.02]
  - [-160.855, 105.6, 823.02]
  - [-160.855, -52.8, 872.9]
  - [-160.855, 52.8, 872.9]
  - [160.855, -52.8, -872.9]
  - [160.855, 52.8, -872.9]
  - [160.855, -105.6, -823.02]
  - [160.855, 0.0, -823.02]
  - [160.855, 105.6, -823.02]
  - [160.855, -105.6, -773.14]
  - [160.855, 0.0, -773.14]
  - [160.855, 105.6, -773.14]
  - [160.855, -52.8, -723.26]
  - [160.855, 52.8, -723.26]
  - [160.855, -52.8, -673.38]
  - [160.855, 52.8, -673.38]
  - [160.855, -105.6, -623.5]
  - [160.855, 0.0, -623.5]
  - [160.855, 105.6, -623.5]
  - [160.855, -105.6, -573.62]
  - [160.855, 0.0, -573.62]
  - [160.855, 105.6, -573.62]
  - [160.855, -52.8, -523.74]
  - [160.855, 52.8, -523.74]
  - [160.855, -52.8, -473.86]
  - [160.855, 52.8, -473.86]
  - [160.855, -105.6, -423.98]
  - [160.855, 0.0, -423.98]
  - [160.855, 105.6, -423.98]
  - [160.855, -105.6, -374.1]
  - [160.855, 0.0, -374.1]
  - [160.855, 105.6, -374.1]
  - [160.855, -52.8, -324.22]
  - [160.855, 52.8, -324.22]
  - [160.855, -52.8, -274.34]
  - [160.855, 52.8, -274.34]
  - [160.855, -105.6, -224.46]
  - [160.855, 0.0, -224.46]
  - [160.855, 105.6, -224.46]
  - [160.855, -105.6, -174.58]
  - [160.855, 0.0, -174.58]
  - [160.855, 105.6, -174.58]
  - [160.855, -52.8, -124.7]
  - [160.855, 52.8, -124.7]
  - [160.855, -52.8, -74.82]
  - [160.855, 52.8, -74.82]
  - [160.855, -105.6, -24.94]
  - [160.855, 0.0, -24.94]
  - [160.855, 105.6, -24.94]
  - [160.855, -105.6, 24.94]
  - [160.855, 0.0, 24.94]
  - [160.855, 105.6, 24.94]
  - [160.855, -52.8, 74.82]
  - [160.855, 52.8, 74.82]
  - [160.855, -52.8, 124.7]
  - [160.855, 52.8, 124.7]
  - [160.855, -105.6, 174.58]
  - [160.855, 0.0, 174.58]
  - [160.855, 105.6, 174.58]
  - [160.855, -105.6, 224.46]
  - [160.855, 0.0, 224.46]
  - [160.855, 105.6, 224.46]
  - [160.855, -52.8, 274.34]
  - [160.855, 52.8, 274.34]
  - [160.855, -52.8, 324.22]
  - [160.855, 52.8, 324.22]
  - [160.855, -105.6, 374.1]
  - [160.855, 0.0, 374.1]
  - [160.855, 105.6, 374.1]
  - [160.855, -105.6, 423.98]
  - [160.855, 0.0, 423.98]
  - [160.855, 105.6, 423.98]
  - [160.855, -52.8, 473.86]
  - [160.855, 52.8, 473.86]
  - [160.855, -52.8, 523.74]
  - [160.855, 52.8, 523.74]
  - [160.855, -105.6, 573.62]
  - [160.855, 0.0, 573.62]
  - [160.855, 105.6, 573.62]
  - [160.855, -105.6, 623.5]
  - [160.855, 0.0, 623.5]
  - [160.855, 105.6, 623.5]
  - [160.855, -52.8, 673.38]
  - [160.855, 52.8, 673.38]
  - [160.855, -52.8, 723.26]
  - [160.855, 52.8, 723.26]
  - [160.855, -105.6, 773.14]
  - [160.855, 0.0, 773.14]
  - [160.855, 105.6, 773.14]
  - [160.855, -105.6, 823.02]
  - [160.855, 0.0, 823.02]
  - [160.855, 105.6, 823.02]
  - [160.855, -52.8, 872.9]
  - [160.855, 52.8, 872.9]
crt:
  normals: [1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 1]
  dimensions:
  - [1106.24, 2.73, 2581.37]
  - [2.73, 184.29, 2581.37]
  - [2.73, 184.29, 2581.37]
  - [1106.24, 184.29, 2.73]
  - [1106.24, 184.29, 2.73]
  - [9.27, 745.15, 864.0]
  - [9.27, 662.28, 800.0]
  - [9.27, 745.15, 800.0]
  - [9.27, 745.15, 864.0]
  - [9.27, 662.28, 800.0]
  - [9.27, 745.15, 800.0]
  - [974.41, 800.0, 16.62]
  - [1016.55, 496.54, 9.27]
  - [944.9735, 1.0, 1521.9]
  positions:
  - [0.0, 617.388, 147.93]
  - [555.265, 496.038, 147.93]
  - [-555.265, 496.038, 147.93]
  - [0.0, 496.038, -1143.4]
  - [0.0, 525.038, 1533.61]
  - [530.355, 35.737, -741.34]
  - [560.19, 4.582, -7.0]
  - [530.355, 35.737, 759.34]
  - [-530.355, 35.737, -741.34]
  - [-560.19, 4.582, -7.0]
  - [-530.355, 35.737, 759.34]
  - [0.0, 48.737, -1126.93]
  - [0.0, 45.753, 1173.855]
  - [-0.0, -346.652, 25.0]
  logical_ids: [30, 31, 32, 33, 34, 40, 41, 42, 43, 44, 45, 46, 47, 50]
